# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxRetweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('max_retweet', models.IntegerField()),
            ],
        ),
    ]
