# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxretweet',
            old_name='tweet_day',
            new_name='day',
        ),
    ]
