# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170109_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxretweet',
            old_name='day',
            new_name='tweet_day',
        ),
    ]
