# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20170109_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxretweet',
            name='tweet_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
